### ISSUE TITLE
No macros working after servers coming back up

### ISSUE THREAD

**Issue by ludicritz** [Sellorio/mega-macro#181]
So with the new changes today none of my macros work anymore. Anyone else having this issue? They're all still there just pressing the buttons doesn't do anything atm

**Comment by Fizgig1973** [comment]
Can confirm. Any macro beyond a basic Blizzard command is not functional currently.

**Comment by Nate603** [comment]
same here, no macros on any characters are working, can't heal :(

**Comment by Lavender-Daydream** [comment]
After I figured out what addon was messing with my normal keybinds, I noticed my macros weren't working.
I won't be able to cast my cat form spells i put in macros. I can't use some of my important spells like regrowth in the macro either. 

Its pretty frustrating when this addon breaks because we usually have spells in those macros. And when the addon breaks and we can't use those macros, we can't use those spells either. Our gameplay is handicapped, or even unplayable. I know you guys (addon developers) aren't purposefully making the addon so it breaks after updates, and that users of the addon aren't entitled to have it fixed on the dime, but hopefully you guys understand what I'm getting at.

**Comment by Lavender-Daydream** [comment]
> same here, no macros on any characters are working, can't heal :(

I'm a healer too. Luckily I can just pull Regrowth, Cenarion Ward, and Wild Growth from my spell book, but I can't use Thrash or Ferocious bite when I go into cat form, so no M+ for me until its fixed. Not sure how it turned out for you, but I can imagine its unplayable with having 2+ healing spells unusable by the macro breaking. I ended up just logging out cause I already had to figure out what other addon is causing my binds not to work and I have to get to bed early. Hopefully they can find out how to fix it before the weekend rolls around and we all have more time to play.

**Comment by ludicritz** [comment]
Just an FYI so you can play while waiting for this to be updated.

I have found that disabling activating abilities on KeyDown fixed the issue. I use ElvUI so it's under ActionBars>General settings and just uncheck the KeyDown checkbox
Hope this helps

> After I figured out what addon was messing with my normal keybinds, I noticed my macros weren't working. I won't be able to cast my cat form spells i put in macros. I can't use some of my important spells like regrowth in the macro either.
> 
> Its pretty frustrating when this addon breaks because we usually have spells in those macros. And when the addon breaks and we can't use those macros, we can't use those spells either. Our gameplay is handicapped, or even unplayable. I know you guys (addon developers) aren't purposefully making the addon so it breaks after updates, and that users of the addon aren't entitled to have it fixed on the dime, but hopefully you guys understand what I'm getting at.

You DO realize that they can't prevent the addons breaking after updates right???? Blizzard changes things on their end and causes these issues. It's done for many reasons like UI improvements/changes, game changes, new zones, new races, etc....
It's a little idiotic to blame the addon creators for this.

**Comment by ludicritz** [comment]
**This was posted on CurseForge if it helps:**

its to do with the securebutton templates changes probably. To the author: [https://us.forums.blizzard.com/en/wow/t/dragonflight-click-bindings-broken/1361972/28](https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fus.forums.blizzard.com%252fen%252fwow%252ft%252fdragonflight-click-bindings-broken%252f1361972%252f28)

 

This specific part might be the cause, to do with a cvar:

GetCVar(“ActionButtonUseKeyDown”)

 

When ActionButtonUseKeyDown is 0:

/click ClickTest works
/click ClickTest LeftButton works
/click ClickTest LeftButton 0 works
/click ClickTest LeftButton 1 doesn’t work
When ActionButtonUseKeyDown is 1:

/click ClickTest doesn’t work
/click ClickTest LeftButton doesn’t work
/click ClickTest LeftButton 0 doesn’t work
/click ClickTest LeftButton 1 works

**Comment by JoeLatte88** [comment]
for what it's worth, `/console ActionButtonUseKeyDown 0` fixes this issue for me..... not using elv and such, so please try it @Lavender-Daydream :)

**Comment by durandal42** [comment]
`/console ActionButtonUseKeyDown 0` is a short-term workaround, but I prefer my abilities to fire on keydown, not keyup, so I need a more permanent fix.
