### ISSUE TITLE
ElvUI Pick up Action Key conflict

### ISSUE THREAD

**Issue by Squimbert** [Sellorio/mega-macro#197]
When using a macro like:

#showtooltip
/use [mod:shift]Mighty Caravan Brutosaur;Grand Expedition Yak

and having the ElvUI Pick up Action Key set to shift (the same modifier in the macro), the macro no longer works.

I'm pretty sure it was something changed in the last ElvUI update.

Are you able to fix this by chance?

I absolutely love your addon <3

**Comment by kodewdle** [comment]
@Squimbert  i doubt this is an issue with this AddOn and not directly a conflict / error in ElvUI itself via:
https://github.com/tukui-org/ElvUI/commit/d2c0a3ceaaf89a8282509ad273d0a1094b02f861

however, there are many issues with Evoker casting, combat related problems, and general "lock actionbar" related problems.
i'd suggest adding your info to this post: https://github.com/tukui-org/ElvUI/issues/706 and obviously, closing the issue here.

**Comment by Squimbert** [comment]
Simpys commenr
