### ISSUE TITLE
Bindpad + Mega Macro

### ISSUE THREAD

**Issue by groin** [Sellorio/mega-macro#90]
Hi, 
i did convert all my macro and created new one with Mega Macro, but when i put them in Binpad panel the code is not recognized and the macro doesn't work.

**Comment by Sellorio** [comment]
Yup, that do happen. I'm afraid I can't help you with that one and Mega Macro isn't a big name yet so Bind Pad probably won't add support for it in the near future.

Effectively, the macro itself is just a stub that calls hidden buttons containing the actual macro text - that's what allows macros to be 1023 characters long instead of 255.

**Comment by groin** [comment]
let makes him a big name!! bindpad is awesome and your addon is unique and amazing and togheter they are so good and i think they complete each other in giving total control on macro/bind.

do you mind to contact bindpad creator eventually?

**Comment by Sellorio** [comment]
I will try
